### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by Sensetivity** [justcoded/yii2-event-listener#1]
Hello. 
I truing to use your package but I face a problem.
When I try to bind event source and handler I get  error on line "\app\models\Call::EVENT_AFTER_INSERT"

> Fatal error: Uncaught Error: Class 'app\models\Call' not found in C:\OpenServer\domains\pocket-crm.loc\config\web.php on line 141

My config:
```PHP
'listener' => [
            'class' => \justcoded\yii2\eventlistener\components\EventListener::class,
            'listeners' => [
                \app\models\Call::class => [
                    \app\models\Call::EVENT_AFTER_INSERT => \app\listeners\CallRegistered::class,
                ],
            ],
            'observers' => [],
        ],
```

**Comment by aprokopenko** [comment]
Hi,

Thanks for sharing this problem.

Could you pls check your composer autoload, that @app alias is registered before merging config file.
It seems composer autoload (or Yii autoload) is not inited yet and it just can't find the correct class.

Furthermore, I never run Yii on Windows, so it can be something with Windows folder separator, don't know.

This is the example from my project, where I use this package:
config/web.php: https://prnt.sc/t9xxnd
config/listener.php: https://prnt.sc/t9xyi6  (i usually use `use` to make it easier to read without namespaces)

And this is my public/index.php file: https://prnt.sc/t9xzo7

I usually use our own starter template with different folder structure. You can ignore folder paths.

So in general:

* web config should have app alias registration
* index.php should load Yii before config merge

If all autoload (yii/composer) is configure correctly - then everything should be fine

**Comment by Sensetivity** [comment]
Thanks for advice. I added alias for @app in index.php and all working.

```PHP
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';

Yii::setAlias('@app', dirname(dirname(__FILE__))); <--- THIS LINE

$config = require __DIR__ . '/../config/web.php';

(new yii\web\Application($config))->run();
```

**Comment by aprokopenko** [comment]
Good to know it helps.

Good luck with your project!

**Comment by aprokopenko** [comment]
Would be great if you give us a star :)
