### ISSUE TITLE
What does the $event param should have?

### ISSUE THREAD

**Issue by gogl92** [justcoded/yii2-event-listener#2]
I want to use an observer for a class but I need to use the `id` of the recorded object but how can I get it? should the `$event` with the model recorded? I'm using a mongodb model so I'm not sure if this is why I'm not able to get the `id` from the event.

```
	/**
	 * Handle after action event
	 *
	 * @param Event $event
	 *
	 * @return void
	 */
	public function after(Event $event)
	{
                  Yii::debug("The ID of the model is -> {$event->id}");
	}

```

**Comment by ArtMin96** [comment]
`$event->sender->id` instead of `$event->id`

**Comment by aprokopenko** [comment]
Hi,

Yes the answer from ArtMin96 is correct.

`$event->sender` is the object you fire event on (for model events - this is a specific model, for controllers - the controller and so on).
